/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const before_Purchaserequisitions_Create = require('./code/before-purchaserequisitions-create');
const before_Purchaseorders_Create_Update = require('./code/before-purchaseorders-create-update');
const before_Goodsreceipts_Create = require('./code/before-goodsreceipts-create');
const after_Invoices_Create = require('./code/after-invoices-create');
const before_Depreciationruns_Create = require('./code/before-depreciationruns-create');
const before_Assetretirements_Create = require('./code/before-assetretirements-create');
const after_Assets_Update = require('./code/after-assets-update');

class asset_accountingSrv extends LCAPApplicationService {
    async init() {

        this.before('CREATE', 'PurchaseRequisitions', async (request) => {
            await before_Purchaserequisitions_Create(request);
        });

        this.before(['CREATE', 'UPDATE'], 'PurchaseOrders', async (request) => {
            await before_Purchaseorders_Create_Update(request);
        });

        this.before('CREATE', 'GoodsReceipts', async (request) => {
            await before_Goodsreceipts_Create(request);
        });

        this.after('CREATE', 'Invoices', async (results, request) => {
            await after_Invoices_Create(results, request);
        });

        this.before('CREATE', 'DepreciationRuns', async (request) => {
            await before_Depreciationruns_Create(request);
        });

        this.before('CREATE', 'AssetRetirements', async (request) => {
            await before_Assetretirements_Create(request);
        });

        this.after('UPDATE', 'Assets', async (results, request) => {
            await after_Assets_Update(results, request);
        });

        return super.init();
    }
}


module.exports = {
    asset_accountingSrv
};